// Turns audio-src/*.wav into src/sfx-data.ts: mono MP3 data URIs the bundle can
// carry inline. Everything ships in one HTML file, and the artifact's CSP won't
// fetch from anywhere, so the samples have to travel as text.
//
//   node scripts/synth.mjs   # render the stand-in bank
//   node scripts/audio.mjs   # encode whatever is in audio-src/
//
// A hand-picked source (Splice, a field recording) goes in as <name>.src.wav —
// synth.mjs then leaves that sound alone and this step normalises and encodes
// it exactly like the rest.
import { readdirSync, readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { execFileSync, spawnSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import ffmpeg from 'ffmpeg-static'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'audio-src')
const OUT = join(ROOT, 'src', 'sfx-data.ts')

// Fanfares carry tone and need the headroom; hits and taps are over in a blink.
const RICH = new Set(['victory', 'defeat', 'ageup', 'bell', 'built', 'muster'])
const HEADROOM_DB = -3.0 // MP3 decoding overshoots the encoded peak; leave it room

const ff = (args) => execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-y', ...args])

// Two passes: measure the true peak, then apply one flat gain. A compressor
// would even out the bank but it also flattens the character out of a hit.
function peakGain(file) {
  const r = spawnSync(ffmpeg, ['-hide_banner', '-i', file, '-af', 'volumedetect', '-f', 'null', '-'],
    { encoding: 'utf8' })
  const m = /max_volume:\s*(-?[\d.]+) dB/.exec(r.stderr ?? '')
  if (!m) throw new Error(`could not measure the peak of ${file}`)
  return HEADROOM_DB - parseFloat(m[1])
}

const tmp = mkdtempSync(join(tmpdir(), 'bw-sfx-'))
const names = readdirSync(SRC)
  .filter(f => f.endsWith('.wav'))
  .map(f => ({ file: join(SRC, f), name: f.replace(/\.src\.wav$|\.wav$/, ''), picked: f.endsWith('.src.wav') }))

// A hand-picked source wins over a synthesised one of the same name.
const bySound = new Map()
for (const s of names) if (!bySound.has(s.name) || s.picked) bySound.set(s.name, s)

const rows = []
let total = 0
for (const { name, file, picked } of [...bySound.values()].sort((a, b) => a.name.localeCompare(b.name))) {
  const mp3 = join(tmp, `${name}.mp3`)
  const gain = peakGain(file)
  // Trim dead air off both ends — Splice one-shots often carry a lot of it.
  const chain = [
    'silenceremove=start_periods=1:start_threshold=-60dB:start_silence=0',
    'areverse',
    'silenceremove=start_periods=1:start_threshold=-60dB:start_silence=0.02',
    'areverse',
    `volume=${gain.toFixed(2)}dB`,
  ].join(',')
  ff(['-i', file, '-af', chain, '-ac', '1', '-ar', '22050',
      '-c:a', 'libmp3lame', '-b:a', RICH.has(name) ? '48k' : '32k', mp3])
  const b64 = readFileSync(mp3).toString('base64')
  total += b64.length
  rows.push({ name, b64, picked, bytes: readFileSync(mp3).length })
}
rmSync(tmp, { recursive: true, force: true })

const body = rows.map(r => `  ${r.name}: '${r.b64}',`).join('\n')
writeFileSync(OUT, `// Generated by scripts/audio.mjs — do not edit by hand.
// Mono MP3 at 22.05kHz, base64 so the whole game stays one file.
export const SFX_DATA: Record<string, string> = {
${body}
}

export const SFX_NAMES = Object.keys(SFX_DATA)
`)

for (const r of rows) {
  console.log(`  ${r.name.padEnd(10)} ${String((r.bytes / 1024).toFixed(1)).padStart(6)} KB${r.picked ? '  (picked)' : ''}`)
}
console.log(`audio: ${rows.length} sounds, ${(total / 1024).toFixed(1)} KB of base64 -> src/sfx-data.ts`)
